version: "3.8"

services:
  bot:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      LAVALINK_HOST: lavalink
    volumes:
      - ./logs:/opt/justbot/logs
    depends_on:
      - lavalink
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    restart: unless-stopped
    env_file: .env
    environment:
      LAVALINK_SERVER_PASSWORD: ${LAVA_AUTH}
      SERVER_PORT: ${LAVA_PORT}